== Development

During product development, multiple choices must be made for how to organize and setup processes for the development, the below sections touch upon various development aspects.

=== Organizing repositories

Organize git repositories according to link:https://en.wikipedia.org/wiki/Conway%27s_law[Conway's Law] and which product options are provided to customers. Cross repository syntax checks are performed in the pull request process using link:https://abaplint.app[abaplint].

=== Example 1

Two separately deployed products, one common library

image::./img/orga1.drawio.svg[]

During packaging, two separately installable artifacts are generated.

Note that the library must be <<_duplicating_code,duplicated>> into each product package.

=== Example 2

One product, two teams with separate responsibilities

image::./img/orga2.drawio.svg[]

=== Quality assurance

All code is managed in git, all changes are reviewed by peers.

Check the link:https://github.com/SAP/styleguides/releases/download/latest/abap-code-review-guide.pdf[ABAP code review guide] for possible setups.

Static analysis is automatically triggered for each link:https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests[pull request], link:https://abaplint.app[abaplint] performs checks according to the team development guidelines.

If the product is developed in SAP BASIS systems higher than the target release, abaplint can help checking the syntax validity of the target language syntax.

Unit tests can be triggered in the pull request using link:https://nuveplatform.com/[Nuve Platform] or using link:https://open-abap.org/[open-abap].

=== Development setups

The development landscape can be organized in various ways, a final setup will typically be a mashup of both central and de-central development.

==== Central Development

One working copy shared by all developers in one system, a single syntax error can impact all developers building and testing in the system

Automatic push to a branch in GitHub can be setup so developers does not have to dig into using git.

Note that a central system will always be required, to perform final testing and packaging.

==== De-central Development

Via link:https://nuveplatform.com/[Nuve Platform] developers can instantiate additional systems, allowing for each branching and testing.

==== transpiler / open-abap

Alternatively, ABAP can be transpiled to JavaScript, allowing code to run on local developer machines or vanilla github actions.

This allows for easy branching, but is developer heavy, as all dependencies must be scaffolded.

Note that this does not replace real systems, which are required for final quality assurance.

==== Summary

[cols="1,1"]
|===
|Setup |Cons

|Central development
|Single working copy

|De-central development
|Extra infrastructure

|transpiler / open-abap
|Extra development effort
|===

=== Duplicating code

If utilizing open or inner source libraries, duplicate objects to stay in control of the dependency. Automatic setups for updating the libraries is recommended.

* link:https://macwright.com/2021/03/11/vendor-by-default.html[Vendor by default]
* link:https://blogs.sap.com/2021/04/20/automagic-standalone-renaming-of-abap-objects/[Automagic standalone renaming of ABAP objects]

=== Reducing footprint into SAP

By reducing the footprint into SAP, eg. reusing of data elements. The product will become more stable, and easier to debug. If a dependency is the real semantic dependency, keep the SAP standard reference.

link:https://abaplint.app[abaplint] will list the unknown void types, plus provide observations in the pull requests when a developer adds new dependencies.

link:https://abapedia.org[abapedia.org] helps identifying which objects are marked as released in the latest Steampunk release.

=== Quality gate

Before packaging and distribution, perform a full system test for each target platform.

link:https://nuveplatform.com/[Nuve Platform] allows easily spinning up different SAP releases for testing.

=== Packaging & Distribution

The product can be delivered to customers using classic transports or via link:https://abapgit.org[abapGit] ZIP files.

abapGit can be used from 7.02 and up, including Steampunk and S/4 HANA Cloud. The customer has full transparency into all changes before performing the import, code review can be done incrementally for each release by the customer. A developer can perform the upload via frontend PC.

Transport files are placed on the application server and imported via classic STMS, note the restrictions if generating transports on different releases than the customer system, link:https://launchpad.support.sap.com/#/notes/1090842[1090842 - Composite SAP Note: Cross-release transports]. The customer cannot review the changes before import, and it requires access to the application server file system to save the transport files.

Note that product development can be done with abapGit, and still employ classic transports for distribution.

=== Versioning/tagging

Everything that is sent to a customer should be tagged in git, this way it is possible to track and reproduce errors locally instead of requiring access to customer systems.

For table contents, customizing and master data, use the abapGit data feature to push the database contents to git.

In case a hotfix is needed for a customer, a branch can be made from the tag, if the customer cannot upgrade to the latest version.

Use a versioning scheme like link:https://semver.org[Semantic Versioning] for the gags.

=== Customer Adjustments

After installation at a customer, the product might need additional adjustments and customizing by the vendor.

Put all all customer adjustments back to git, possibly a repository for each customer, depending on the actual content.

Do not adjust the product code in the customer system, instead provide the customer with a new release(triggering new versioning), or alternatively provide enhancement points in the product for customer-specific adjustments in customer namespace.